### ISSUE TITLE
Add instructions

### ISSUE THREAD

**Issue by TCG85** [TCG85/demo-site#2]
Add **instructions** to HTML file to customize this for your own artwork.

- [x] Research different AI tools
- [x] Generate the AI text
- [x] Copy & Paste the text.

```css
h1 {color: red; }
```
